services:
  testdb:
    image: postgres:16
    environment:
      POSTGRES_DB: logger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testdb
    volumes:
      - devpgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logger"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./FoolOfRESTAPI
    environment:
      - POSTGRES_CONNECTION_STRING=Host=testdb;Port=5432;Database=logger;Username=postgres;Password=testdb
      - APIKEY=testkey
      - TOKEN=${TOKEN}
      - CONNECTION_STRING=host=testdb port=5432 dbname=logger user=postgres password=testdb
    depends_on:
      testdb:
        condition: service_healthy
    ports:
      - "5001:5001"

  web:
    build:
      context: ./FoolOfRESTWeb
    environment:
      - API_URL=http://api:5001/
      - APIKEY=testkey
    depends_on:
      - api
    ports:
      - "8080:8080"

volumes:
  devpgdata:
