services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: logger
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  testdb:
    image: postgres:16
    environment:
      POSTGRES_DB: logger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testdb
    volumes:
      - devpgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
volumes:
  devpgdata:
  pgdata:
